name: MCTrackerVote
version: '${project.version}'
main: ir.mctracker.core.MCTrackerVote
api-version: 1.13
authors: [ Cipher, Alijk, GitContributors ]
description: https://mctracker.ir/ vote handling plugin
website: https://mctracker.ir/

commands:
  mctracker:
    description: Main command of the plugin
    usage: /<command>
    aliases:
      - tracker
  vote:
    description: Vote command
    usage: /<command>

permissions:
  mctracker.*:
    children:
      mctracker.commands.reload: true
      mctracker.commands.vote: true